CREATE TABLE `investment`.`morningstar_book_value_per_share`(
  `STOCK` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VERSION` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TS` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `BOOK_VALUE_PER_SHARE` DOUBLE NOT NULL,
  PRIMARY KEY(`STOCK`, `DATE`, `VERSION`)
) ENGINE = InnoDB;

CREATE TABLE `investment`.`morningstar_annual_net_income`(
  `STOCK` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VERSION` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TS` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `NET_INCOME_MIL` DOUBLE NOT NULL,
  PRIMARY KEY(`STOCK`, `DATE`, `VERSION`)
) ENGINE = InnoDB;


CREATE TABLE `investment`.`morningstar_annual_revenue`(
  `STOCK` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATE` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `VERSION` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `TS` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `REVENUE_MIL` DOUBLE NOT NULL,
  PRIMARY KEY(`STOCK`, `DATE`, `VERSION`)
) ENGINE = InnoDB;


CREATE TABLE `investment`.`yahoo_finance`(
  `STOCK` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `DATETIME` DATETIME NOT NULL,
  `VERSION` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `PRICE` DOUBLE DEFAULT NULL,
  `DAYS_HIGH` DOUBLE DEFAULT NULL,
  `DAYS_LOW` DOUBLE DEFAULT NULL,
  `PRICE_CHANGE` DOUBLE DEFAULT NULL,
  `VOLUME` DOUBLE DEFAULT NULL,
  `MARKET_CAP_IN_MILLIONS` DOUBLE DEFAULT NULL,
  `BOOK_VALUE` DOUBLE DEFAULT NULL,
  `EBITDA_IN_MILLIONS` DOUBLE DEFAULT NULL,
  `DIVIDEND_SHARE` DOUBLE DEFAULT NULL,
  `DIVIDEND_YIELD` DOUBLE DEFAULT NULL,
  `EARNING_SHARE` DOUBLE DEFAULT NULL,
  `PRICE_BOOK` DOUBLE DEFAULT NULL,
  `PRICE_SALES` DOUBLE DEFAULT NULL,
  PRIMARY KEY(`STOCK`, `DATE`, `VERSION`)
) ENGINE = InnoDB;
